######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 30 02:17:09 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += aghphonedialog.h
FORMS += aghphonedialog.ui
SOURCES += aghphonedialog.cpp main.cpp
