######################################################################
# Automatically generated by qmake (2.01a) pon. cze 30 14:44:08 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . 

# Input
HEADERS += aghphonedialog.h
FORMS += aghphonedialog.ui
SOURCES += aghphonedialog.cpp main.cpp
